import type { Config } from 'tailwindcss';

export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'selector',
  theme: {
    fontFamily: {
      sans: ['var(--font-raleway)', 'Segoe UI', 'Roboto', 'Helvetica', 'Arial', 'sans-serif'],
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1.5rem',
        md: '2rem',
        lg: '3rem',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
      },
    },
    extend: {
      padding: {
        'header-height': 'calc(64px + calc(var(--header-height)/2))',
      },
      margin: {
        'header-height': 'calc(64px + calc(var(--header-height)/2))',
      },
      fontSize: {
        '4xl': ['2.25rem', { lineHeight: '1.3' }],
        '3xl': ['1.875rem', { lineHeight: '1.3' }],
        '2xl': ['1.5rem', { lineHeight: '1.5' }],
        xl: ['1.25rem', { lineHeight: '1.5' }],
        lg: ['1.125rem', { lineHeight: '1.5' }],
        base: ['1rem', { lineHeight: '1.5' }],
        sm: ['0.875rem', { lineHeight: '1.6' }],
      },
      colors: {
        // Semantic colors
        background: 'rgba(var(--background))',
        foreground: 'rgba(var(--foreground))',
        primary: {
          DEFAULT: 'rgba(var(--primary))',
          foreground: 'rgba(var(--primary-foreground))',
        },
        'accent-lime': 'rgba(var(--accent-lime))',
        'accent-electric-blue': 'rgba(var(--accent-electric-blue))',
        'accent-violet': 'rgba(var(--accent-violet))',
        'card-bg': 'rgba(var(--card-bg))',
        'sidebar-bg': 'rgba(var(--sidebar-bg))',
        'setting-button-color': 'rgba(var(--setting-button-color))',
        'setting-button-color-hover': 'rgba(var(--setting-button-color-hover))',
        'card-body-text-color': 'rgba(var(--card-body-text-color))',
        'toast-bg': 'rgba(var(--toast-bg))',
        'toast-border-color': 'rgba(var(--toast-border-color))',

        // Original color scales
        'rich-black': {
          DEFAULT: 'rgba(var(--rich-black))',
          100: 'rgba(var(--rich-black-100))',
          200: 'rgba(var(--rich-black-200))',
          300: 'rgba(var(--rich-black-300))',
          400: 'rgba(var(--rich-black-400))',
          500: 'rgba(var(--rich-black-500))',
          600: 'rgba(var(--rich-black-600))',
          700: 'rgba(var(--rich-black-700))',
          800: 'rgba(var(--rich-black-800))',
          900: 'rgba(var(--rich-black-900))',
        },
        lime: {
          DEFAULT: 'rgba(var(--lime))',
          100: 'rgba(var(--lime-100))',
          200: 'rgba(var(--lime-200))',
          300: 'rgba(var(--lime-300))',
          400: 'rgba(var(--lime-400))',
          500: 'rgba(var(--lime-500))',
          600: 'rgba(var(--lime-600))',
          700: 'rgba(var(--lime-700))',
          800: 'rgba(var(--lime-800))',
          900: 'rgba(var(--lime-900))',
        },
        violet: {
          DEFAULT: 'rgba(var(--violet))',
          100: 'rgba(var(--violet-100))',
          200: 'rgba(var(--violet-200))',
          300: 'rgba(var(--violet-300))',
          400: 'rgba(var(--violet-400))',
          500: 'rgba(var(--violet-500))',
          600: 'rgba(var(--violet-600))',
          700: 'rgba(var(--violet-700))',
          800: 'rgba(var(--violet-800))',
          900: 'rgba(var(--violet-900))',
        },
        'electric-blue': {
          DEFAULT: 'rgba(var(--electric-blue))',
          100: 'rgba(var(--electric-blue-100))',
          200: 'rgba(var(--electric-blue-200))',
          300: 'rgba(var(--electric-blue-300))',
          400: 'rgba(var(--electric-blue-400))',
          500: 'rgba(var(--electric-blue-500))',
          600: 'rgba(var(--electric-blue-600))',
          700: 'rgba(var(--electric-blue-700))',
          800: 'rgba(var(--electric-blue-800))',
          900: 'rgba(var(--electric-blue-900))',
        },
        'cosmic-latte': {
          DEFAULT: 'rgba(var(--cosmic-latte))',
          100: 'rgba(var(--cosmic-latte-100))',
          200: 'rgba(var(--cosmic-latte-200))',
          300: 'rgba(var(--cosmic-latte-300))',
          400: 'rgba(var(--cosmic-latte-400))',
          500: 'rgba(var(--cosmic-latte-500))',
          600: 'rgba(var(--cosmic-latte-600))',
          700: 'rgba(var(--cosmic-latte-700))',
          800: 'rgba(var(--cosmic-latte-800))',
          900: 'rgba(var(--cosmic-latte-900))',
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
